### ISSUE TITLE
how would you cancel requests on component unmount?

### ISSUE THREAD

**Issue by cezarneaga** [bghveding/use-fetch#5]
am i missing something from the api?

**Comment by bghveding** [comment]
Hey

It should already be being doing that: https://github.com/bghveding/use-fetch/blob/master/src/useFetch.js#L231. Are you experiencing otherwise?

Or are you referring to a situation where a component has unmounted, but a request is resolved after the component has unmounted?

**Comment by cezarneaga** [comment]
sorry, the issue was with the react router.
